apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rpp
  name: rpp-prod-rust-deployment
  namespace: rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpp
  strategy: {}
  template:
    metadata:
      labels:
        app: rpp
    spec:
      containers:
      - image: ghcr.io/alexemanuelol/rustplusplus:master
        name: rpp
        resources: {}
        env:
        - name: RPP_DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: credentials-prod-rust-secret
              key: discord-client-id
        - name: RPP_DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: credentials-prod-rust-secret
              key: discord-token
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: maps
          mountPath: /app/maps
        - name: instances
          mountPath: /app/instances
        - name: credentials
          mountPath: /app/credentials
      volumes:
      - name: credentials
        persistentVolumeClaim:
          claimName: credentials-prod-rust-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: logs-prod-rust-pvc
      - name: maps
        persistentVolumeClaim:
          claimName: maps-prod-rust-pvc
      - name: instances
        persistentVolumeClaim:
          claimName: instances-prod-rust-pvc