apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dispatcharr
  name: dispatcharr-prod-media-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr
  strategy: {}
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      securityContext:
        fsGroup: 10000
        runAsGroup: 10000
        runAsNonRoot: true
        runAsUser: 10000
        seccompProfile:
          type: RuntimeDefault
        readOnlyRootFilesystem: true
      automountServiceAccountToken: false
      containers:
      - securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        image: ghcr.io/dispatcharr/dispatcharr:latest
        name: dispatcharr
        envFrom:
        - configMapRef:
            name: dispatcharr-prod-media-config
        ports:
          - containerPort: 9191
            name: http
            protocol: TCP
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dispatcharr-prod-media-pvc