apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dispatcharr
  name: dispatcharr-prod-media-web-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      containers:
        - name: web
          image: ghcr.io/dispatcharr/dispatcharr:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: password
          envFrom:
          - configMapRef:
              name: dispatcharr-prod-media-web-config
          ports:
            - containerPort: 9191
              name: http
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-prod-media-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dispatcharr-celery
  name: dispatcharr-prod-media-celery-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr-celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dispatcharr-celery
    spec:
      containers:
        - name: celery
          image: ghcr.io/dispatcharr/dispatcharr:latest
          command: 
            - "/app/docker/entrypoint.celery.sh"
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dispatcharr-prod-media-pg-app
                  key: password
          envFrom:
            - configMapRef:
                name: dispatcharr-prod-media-celery-config
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-prod-media-pvc