apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-prod-ingest-pvc
  namespace: ingest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
