apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-hdd
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  diskSelector: "slow" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libary-prod-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-prod-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
