all:
  children:
    pve:
      hosts:
        pve-j0zk2w2: 
          ansible_host: 192.168.10.240
        pve-1fdq713:
          ansible_host: 192.168.10.241
        pve-dh16933:
          ansible_host: 192.168.10.242
        # wyse-4kty903:
        #   ansible_host: 192.168.10.245
    dns:
      hosts:
        # ns1:
        #   ansible_host: 192.168.10.247
        ns1:
          ansible_host: 192.168.10.140
        ns2:
          ansible_host: 192.168.10.166
    nfs:
      hosts:
        nfs:
          ansible_host: 192.168.10.197