---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-prod-ingest-pvc
  namespace: ingest
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: ingest-prod-shared-pv
