apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-helm-repos
  namespace: default
spec:
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/infrastructure/helm-repos
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-namespaces
  namespace: default
spec:
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/infrastructure/namespaces
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loadbalancer-controller
  namespace: default
spec:
  dependsOn:
    - name: infra-helm-repos
    - name: infra-namespaces
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/infrastructure/loadbalancer/controller
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loadbalancer-config
  namespace: default
spec:
  dependsOn:
    - name: loadbalancer-controller
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/infrastructure/loadbalancer/config
  prune: true
  wait: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: infra-controllers
#   namespace: default
# spec:
#   dependsOn:
#     - name: loadbalancer-config
#   interval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   path: ./flux/infrastructure/controllers
#   prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: infra-configs
#   namespace: default
# spec:
#   dependsOn:
#     - name: infra-controllers
#   interval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   path: ./flux/infrastructure/configs
#   prune: true
