apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr-prod-media-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy: {}
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - image: docker.io/linuxserver/sonarr
        name: sonarr
        ports:
          - containerPort: 8989
            name: http
            protocol: TCP
        resources: {}
        volumeMounts:
        - name: app-data
          mountPath: /config
        - name: media-data
          mountPath: /data
        - name: ingest-data
          mountPath: /downloads
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: sonarr-prod-media-pvc
      - name: media-data
        persistentVolumeClaim:
          claimName: media-prod-media-pvc
      - name: ingest-data
        persistentVolumeClaim:
          claimName: ingest-prod-media-pvc
