apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin-prod-media-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    rollingUpdate: 
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - image: docker.io/jellyfin/jellyfin
        name: jellyfin
        envFrom:
        - configMapRef:
            name: jellyfin-prod-media-config
        ports:
          - containerPort: 8096
            name: http
            protocol: TCP
        resources: {}
        volumeMounts:
        - name: app-data
          mountPath: /config
        - name: media-data
          mountPath: /media
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: jellyfin-prod-media-pvc
      - name: media-data
        persistentVolumeClaim:
          claimName: libary-prod-media-pvc