---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-frontend-proxy-prod-media-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-frontend-proxy-prod-media-deployment
  template:
    metadata:
      labels:
        app: qbittorrent-frontend-proxy-prod-media-deployment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: qbittorrent-frontend-proxy-prod-media-config
