apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent-prod-media-statefulset
  namespace: media
spec:

  serviceName: "qbittorrent-prod-media-svc"
  replicas: 3
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - image: docker.io/linuxserver/qbittorrent
        name: qbittorrent
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 6881
            protocol: TCP
          - containerPort: 6881
            protocol: UDP
        resources:
          requests:
            cpu: '0.5'
            memory: 2048Mi
        volumeMounts:
        - name: data
          mountPath: /config/qBittorrent/qBittorrent.conf
          subPath: qBittorrent.conf
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: data
        configMap:
          name: qbittorrent-prod-media-config
      - name: downloads
        emptyDir: {}