apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr-prod-media-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy: {}
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - image: docker.io/linuxserver/radarr
        name: radarr
        ports:
          - containerPort: 7878
            name: http
            protocol: TCP
        resources: {}
        volumeMounts:
        - name: app-data
          mountPath: /config
        - name: media-data
          mountPath: /movies
        - name: ingest-data
          mountPath: /downloads
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: radarr-prod-media-pvc
      - name: media-data
        nfs:
          server: 192.168.10.197
          path: /srv/nfs/movies
      - name: ingest-data
        persistentVolumeClaim:
          claimName: ingest-prod-media-pvc

