apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-prod-data-pvc
  namespace: longhorn-system
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fs-prod-data-svc
  namespace: longhorn-system
spec:
  selector:
    longhorn.io/component: share-manager
  ports:
    - protocol: TCP
      port: 2049