apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-prod-shared-pvc
  namespace: longhorn-system
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  volumeName: ingest-prod-shared-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ingest-prod-shared-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: "ingest-prod-shared-pvc"