apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-prod-shared
  namespace: longhorn-system
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  volumeName: ingest-prod-shared-pv
  resources:
    requests:
      storage: 5Gi
