apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  strategy: {}
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - image: ghcr.io/home-assistant/home-assistant:stable
        name: home-assistant
        env:
          - name: TZ
            value: Europe/London
        ports:
          - containerPort: 8123
            name: http
            protocol: TCP
          - containerPort: 4357
            protocol: TCP
          - containerPort: 51827
            protocol: TCP
          - containerPort: 1900
            protocol: UDP
          - containerPort: 5353
            protocol: UDP
          - containerPort: 5683
            protocol: UDP      
        resources: {}
status: {}
