apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: homeassistant
spec:
  selector:
      app: homeassistant
  ports:
    - port: 8123
      targetPort: http
      name: frontend
      protocol: TCP
    - port: 4357
      name: home-assistant-observer-port
      targetPort: 4357
      protocol: TCP
    - port: 51827
      name: homekit-integration
      targetPort: 51827
      protocol: TCP     
    - port: 1900
      name: ssdp-discovery-upnp
      targetPort: 1900
      protocol: UDP
    - port: 5353
      name: mdns-zeroconf
      targetPort: 5353
      protocol: UDP
    - port: 5683
      name: unicast-coap
      targetPort: 5683
      protocol: UDP      