name: Scan IaC with KICS
permissions:
  security-events: write
  contents: read

on: [ pull_request ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - uses: actions/checkout@v6.0.2
      - run: mkdir -p results-dir
      - name: run kics Scan
        uses: checkmarx/kics-action@v2.1.20
        with:
          path: 'terraform,manifests,ansible'
          output_path: results-dir
          ignore_on_exit: results
          output_formats: 'sarif'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4.35.2
        with:
          sarif_file: results-dir/results.sarif

